apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: OPENAI_API_KEY
              value: # OPEN AI KEY 
            - name: GOOGLE_API_KEY
              value: # GOOGLE API KEY
            - name: PORT
              value: "8080"