
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
   OPENAI_API_KEY: <base64-encoded-openai-key>
   GOOGLE_API_KEY: <base64-encoded-google-api-key>
   FLAG: a2VzaGF2 

# Use the following command to generate the base64 version of your actual values:
# --> echo -n 'your-api-key-here' | base64
