apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
type: Opaque
data:
  NEXT_PUBLIC_MAPBOX_TOKEN:  <base64-encoded-mapbox-key>
  FLAG: a2VzaGF2 


# Use the following command to generate the base64 version of your actual values:
# --> echo -n 'your-api-key-here' | base64
